server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

spring:
  profiles:
    active: dev
  banner:
    location: classpath:banner/banner.txt
  servlet:
    multipart:
      max-file-size: 2MB # 文件上传大小限制
      max-request-size: 2MB # 文件最大请求限制，用于批量上传

# mybatis
mybatis:
  type-aliases-package: com.maozhua.pojo
  mapper-locations: classpath:mapper/*.xml

# 通用mapper工具配置
mapper:
  mappers: com.maozhua.my.mapper.MyMapper   # 配置MyMapper，包含了一些封装好的CRUD方法
  not-empty: false                          # 在进行数据库操作的时候，username != null 是否会追加 username != ''
  identity: MYSQL


# 分页插件助手的配置
pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true

# 日志级别
logging:
  level:
    root: info